trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SQLSERVER: 'preethampreethamhw8server.database.windows.net'   # <— yours
  DBNAME: 'HW8PipelineDB'                                      # <— yours
  SQLUSER: 'preetham'                                        # add in DevOps Variables
  SQLPASSWORD: 'Password123!'                                # add in DevOps Variables (secret)

steps:
- checkout: self

# Install Microsoft ODBC Driver 18 for SQL Server + build deps
- script: |
    set -e
    sudo apt-get update
    sudo apt-get install -y curl gnupg apt-transport-https
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
    python3 -m pip install --upgrade pip
    python3 -m pip install pandas sqlalchemy pyodbc
  displayName: 'Install ODBC driver and Python libs'

# (Optional) show installed drivers
- script: |
    python3 - << 'PY'
    import pyodbc
    print("Drivers:", pyodbc.drivers())
    PY
  displayName: 'Check available ODBC drivers'

# Run the loader
- script: |
    python3 load_data.py
  displayName: 'Load CSV data into Azure SQL'
  env:
    AZ_SQLSERVER: $(SQLSERVER)
    AZ_DBNAME: $(DBNAME)
    AZ_SQLUSER: $(SQLUSER)
    AZ_SQLPASSWORD: $(SQLPASSWORD)
